paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /sci/archive/michall/roeizucker/huggingface_modles_cache/datasets/generator
  raw_data_paths:
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652233_Liver-Hepatocytes-Z000000R3.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652235_Liver-Hepatocytes-Z0000043Q.hg38.bigwig
  per_variant_data_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/window_split_with_600/T3_per_varaint_variabilitywindow_split_with_600_seq_600_datasets.csv
task:
  type: cpg_seperating_sites
  chromosomes:
  - chr5
  test_size: 0
  variability_type: std
  variant_seperation_type: quantile
  variant_seperation_threshold: 0.09
  output_per_variant_data: true
  output_window_data: false
  seq_size: 600
testing_params:
  test_mode: false
random_state: 42
verbose: true
