paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /sci/archive/michall/roeizucker/huggingface_modles_cache/datasets/generator
  variant_file_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/R3_per_varaint_variability_HP_optimization_multi_project_config_datasets.csv
  model_paths:
  - /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/R3_pretrain_HP_optimization_multi_project_config_lr_1e-07_bs_2/epoch-3-step-146847
  - /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/R3_epoch-3-step-146847_retrain_HP_optimization_multi_project_config_lr_1e-07_bs_2/epoch-5-step-65785
  - /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/R3_epoch-3-step-146847_retrain_HP_optimization_multi_project_config_lr_1e-07_bs_2/epoch-1-step-13157
  - /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/R3_epoch-3-step-146847_retrain_HP_optimization_multi_project_config_lr_1e-07_bs_2/epoch-3-step-39471
  - /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/R3_epoch-3-step-146847_retrain_HP_optimization_multi_project_config_lr_1e-07_bs_2/epoch-2-step-26314
  - /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/R3_epoch-3-step-146847_retrain_HP_optimization_multi_project_config_lr_1e-07_bs_2/epoch-4-step-52628
  dataset_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/R3_retrain_HP_optimization_multi_project_config_datasets_test
task:
  task_type: cpg_evaluation
  sub_task: evaluate_multiple_checkpoints
  analysis_name: R3_epoch-3-step-146847_eval_HP_optimization_multi_project_config_lr_1e-07_bs_2
  top_rows: -1
  use_variant_file: true
  vriant_grouping_method: bins
  number_of_bins: 3
testing_params:
  test_mode: false
random_state: 42
verbose: true
model:
  model_name: nucleotide-transformer-2.5b-multi-species
  model_repo: InstaDeepAI
  model_type: regression_analysis
  blank_label: -100
  use_lora: false
  freeze_mode: false
  num_labels: 1
