paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /sci/archive/michall/roeizucker/huggingface_modles_cache/datasets/generator
  variant_file_path: /sci/archive/michall/roeizucker/Tom_project/created_datasets/Liver-Hepatocytes_Kaplan_lab_without_min1.csv
  model_paths:
  - /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/3Q_pretrain_revert_test/epoch-1-step-33261
  dataset_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/3Q_retrain_revert_test_test
task:
  task_type: cpg_evaluation
  sub_task: evaluate_multiple_checkpoints
  analysis_name: 3Q_revert_test_manual
  top_rows: -1
  use_variant_file: true
  vriant_grouping_method: bins
  number_of_bins: 3
testing_params:
  test_mode: false
random_state: 42
verbose: true
model:
  model_name: nucleotide-transformer-2.5b-multi-species
  model_repo: InstaDeepAI
  model_type: regression_analysis
  blank_label: -100
  use_lora: false
  freeze_mode: false
  num_labels: 1
