paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /sci/archive/michall/roeizucker/huggingface_modles_cache/datasets/generator
  train_dataset_path:
  - /sci/archive/michall/roeizucker/huggingface_datasets_dir/R3_retrain_HP_optimization_multi_project_config_datasets_train
  output_dir: /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/R3_epoch-2-step-48950_retrain_HP_optimization_multi_project_config_lr_1e-07_bs_4
  trained_model_path: /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/R3_pretrain_HP_optimization_multi_project_config_lr_1e-07_bs_4/epoch-2-step-48950
task:
  task_type: cpg_retraining
  analysis_name: R3_epoch-2-step-48950_retrain_HP_optimization_multi_project_config_lr_1e-07_bs_4
  top_rows: -1
testing_params:
  test_mode: false
random_state: 42
verbose: true
model:
  model_name: nucleotide-transformer-2.5b-multi-species
  model_repo: InstaDeepAI
  model_type: regression_analysis
  blank_label: -100
  use_lora: false
  freeze_mode: false
  num_labels: 1
train:
  load_best_model_at_end: false
  num_train_epochs: 5
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 2
  learning_rate: 1.0e-07
  metric_for_best_model: mse
  save_stratagy: steps
  max_grad_norm: 1
  number_of_steps: 10000
  save_total_limit: 2
  add_epoch_end_save_callback: true
  save_at_end: false
  continue_from_last: true
