paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /sci/archive/michall/roeizucker/huggingface_modles_cache/datasets/generator
  raw_data_path: /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652237_Liver-Hepatocytes-Z0000044M.hg38.bigwig
  intermediate_train_data_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/temp_train2025-10-1020:00:48.817336.csv
  intermediate_test_data_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/temp_test2025-10-1020:00:48.817336.csv
  hf_dataset_train_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/GSM5652237_Liver-Hepatocytes-Z0000044M_retrain_7.5param_train
  hf_dataset_test_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/GSM5652237_Liver-Hepatocytes-Z0000044M_retrain_7.5param_test
task:
  type: cpg_extraction
  assembly: HG38
  value_column: methyl_rate
  input_mode: raw_input
  seq_size: 5400
  test_size: 0.2
  blank_label: -100
  use_fasta: true
  shuffle: true
  chromosomes:
  - chr1
  tokenizer_name: InstaDeepAI/nucleotide-transformer-2.5b-multi-species
  output_preprocessed_data: false
  output_intermediate_data: true
  output_hf_dataset: true
  window_type: standart_no_overlap
  train_test_seperation: random_sample_filtration
  clear_generator_cache: true
testing_params:
  test_mode: false
random_state: 42
verbose: true
