paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /sci/archive/michall/roeizucker/huggingface_modles_cache/datasets/generator
  variant_file_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/_different_epoch_length_dataset_override_test/3Q_per_varaint_variability_different_epoch_length_dataset_override_test_seq_600_datasets.csv
  model_paths:
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_different_epoch_length_dataset_override_test/3Q_no_pretraining_retrain_different_epoch_length_dataset_override_test_lr_1e-06_bs_2_seq_600_testsize_0.2/epoch-1-step-120169
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_different_epoch_length_dataset_override_test/3Q_no_pretraining_retrain_different_epoch_length_dataset_override_test_lr_1e-06_bs_2_seq_600_testsize_0.2/epoch-3-step-360507
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_different_epoch_length_dataset_override_test/3Q_no_pretraining_retrain_different_epoch_length_dataset_override_test_lr_1e-06_bs_2_seq_600_testsize_0.2/epoch-4-step-480676
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_different_epoch_length_dataset_override_test/3Q_no_pretraining_retrain_different_epoch_length_dataset_override_test_lr_1e-06_bs_2_seq_600_testsize_0.2/epoch-2-step-240338
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_different_epoch_length_dataset_override_test/3Q_no_pretraining_retrain_different_epoch_length_dataset_override_test_lr_1e-06_bs_2_seq_600_testsize_0.2/epoch-5-step-600845
  dataset_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/_different_epoch_length_dataset_override_test/3Q_retrain_different_epoch_length_dataset_override_test_seq_600_datasets_test
task:
  task_type: cpg_evaluation
  sub_task: evaluate_multiple_checkpoints
  analysis_name: 3Q_no_pretraining_eval_different_epoch_length_dataset_override_test_lr_1e-06_bs_2_seq_600_testsize_0.2
  top_rows: -1
  use_variant_file: true
  vriant_grouping_method: bins
  number_of_bins: 5
  base_suffix: _different_epoch_length_dataset_override_test
testing_params:
  test_mode: false
random_state: 42
verbose: true
model:
  model_name: nucleotide-transformer-2.5b-multi-species
  model_repo: InstaDeepAI
  model_type: regression_analysis
  blank_label: -100
  use_lora: false
  freeze_mode: false
  num_labels: 1
  lora_over_finetuned: false
