paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /sci/archive/michall/roeizucker/huggingface_modles_cache/datasets/generator
  raw_data_paths:
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652233_Liver-Hepatocytes-Z000000R3.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652235_Liver-Hepatocytes-Z0000043Q.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652236_Liver-Hepatocytes-Z0000044H.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652237_Liver-Hepatocytes-Z0000044M.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652238_Liver-Hepatocytes-Z00000431.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652212_Heart-Cardiomyocyte-Z0000044G.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652213_Heart-Cardiomyocyte-Z0000044K.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652214_Heart-Cardiomyocyte-Z0000044N.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652215_Heart-Cardiomyocyte-Z0000044P.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652216_Heart-Cardiomyocyte-Z0000044Q.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652217_Heart-Cardiomyocyte-Z0000044R.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652342_Bladder-Epithelial-Z000000QM.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652343_Bladder-Epithelial-Z000000QP.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652344_Bladder-Epithelial-Z0000043F.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652345_Bladder-Epithelial-Z0000044L.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652346_Bladder-Epithelial-Z00000450.hg38.bigwig
  per_variant_data_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/real_tissue_triplet/LH_T3_per_varaint_variability_real_tissue_triplet_seq_5400_datasets.csv
task:
  type: cpg_seperating_sites
  chromosomes:
  - chr5
  test_size: 0
  variability_type: std
  variant_seperation_type: quantile
  variant_seperation_threshold: 0.09
  output_per_variant_data: true
  output_window_data: false
  seq_size: 5400
testing_params:
  test_mode: false
random_state: 42
verbose: true
