paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /home/users/roeizucker/.cache/huggingface/datasets/generator
  raw_data_paths:
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652225_Cortex-Neuron-Z0000042F.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652226_Cortex-Neuron-Z0000042H.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652227_Cortex-Neuron-Z0000042J.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652228_Cortex-Neuron-Z0000042M.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652229_Cortex-Neuron-Z0000042P.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652230_Cortex-Neuron-Z0000042K.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652232_Cortex-Neuron-Z000000TD.hg38.bigwig
  per_variant_data_path: /cs/usr/roeizucker/new_storage/huggingface_datasets_dir/rerun_20260517_112438/_Cortex-Neuron_kmer_rerun_20260517_112438/Z000000TF_per_varaint_variability_Cortex-Neuron_kmer_rerun_20260517_112438_seq_600_datasets.csv
task:
  type: cpg_seperating_sites
  chromosomes:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  test_size: 0
  variability_type: std
  variant_seperation_type: quantile
  variant_seperation_threshold: 0.09
  output_per_variant_data: true
  output_window_data: false
  seq_size: 600
testing_params:
  test_mode: false
random_state: 42
verbose: true
