paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /sci/archive/michall/roeizucker/huggingface_modles_cache/datasets/generator
  train_dataset_path:
  - /sci/archive/michall/roeizucker/huggingface_datasets_dir/_sixteen_shards_of_adonalsium_liver/R3_pretrain_sixteen_shards_of_adonalsium_liver_seq_5400_datasets_train
  - /sci/archive/michall/roeizucker/huggingface_datasets_dir/_sixteen_shards_of_adonalsium_liver/T3_pretrain_sixteen_shards_of_adonalsium_liver_seq_5400_datasets_train
  - /sci/archive/michall/roeizucker/huggingface_datasets_dir/_sixteen_shards_of_adonalsium_liver/4H_pretrain_sixteen_shards_of_adonalsium_liver_seq_5400_datasets_train
  - /sci/archive/michall/roeizucker/huggingface_datasets_dir/_sixteen_shards_of_adonalsium_liver/4M_pretrain_sixteen_shards_of_adonalsium_liver_seq_5400_datasets_train
  - /sci/archive/michall/roeizucker/huggingface_datasets_dir/_sixteen_shards_of_adonalsium_liver/31_pretrain_sixteen_shards_of_adonalsium_liver_seq_5400_datasets_train
  output_dir: /sci/labs/michall/roeizucker/trained_huggingface_models_location/_sixteen_shards_of_adonalsium_liver/3Q_pretrain_sixteen_shards_of_adonalsium_liver_lr_1e-06_bs_2_seq_5400_testsize_0.2
task:
  task_type: cpg_training
  analysis_name: 3Q_pretrain_sixteen_shards_of_adonalsium_liver_lr_1e-06_bs_2_seq_5400_testsize_0.2
  top_rows: -1
testing_params:
  test_mode: false
random_state: 42
verbose: true
model:
  model_name: nucleotide-transformer-2.5b-multi-species
  model_repo: InstaDeepAI
  model_type: regression_analysis
  blank_label: -100
  use_lora: false
  freeze_mode: false
  num_labels: 1
train:
  load_best_model_at_end: false
  num_train_epochs: 2
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  learning_rate: 1e-06
  metric_for_best_model: mse
  save_stratagy: steps
  lora_over_finetuned: false
  load_dataset_to_memory: true
  max_grad_norm: 1
  number_of_steps: 10000
  save_total_limit: 2
  add_epoch_end_save_callback: true
  save_at_end: false
  continue_from_last: true
