paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /sci/archive/michall/roeizucker/huggingface_modles_cache/datasets/generator
  raw_data_path: /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652233_Liver-Hepatocytes-Z000000R3.hg38.bigwig
  intermediate_train_data_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/_HPO_after_time_improvment/temp_train2026-02-0608:50:29.424212.csv
  intermediate_test_data_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/_HPO_after_time_improvment/temp_test2026-02-0608:50:29.424212.csv
  hf_dataset_train_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/_HPO_after_time_improvment/R3_pretrain_HPO_after_time_improvment_datasets_train
  hf_dataset_test_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/_HPO_after_time_improvment/R3_pretrain_HPO_after_time_improvment_datasets_test
  variant_file_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/_HPO_after_time_improvment/R3_per_varaint_variability_HPO_after_time_improvment_datasets.csv
task:
  type: cpg_extraction
  assembly: HG38
  value_column: methyl_rate
  input_mode: raw_input
  seq_size: 5400
  test_size: 0
  blank_label: -100
  use_fasta: true
  shuffle: true
  chromosomes:
  - chr5
  tokenizer_name: InstaDeepAI/nucleotide-transformer-2.5b-multi-species
  output_preprocessed_data: false
  output_intermediate_data: true
  output_hf_dataset: true
  window_type: standart_no_overlap
  train_test_seperation: kmer_sample_filtration
  clear_generator_cache: true
  replace_min1: true
testing_params:
  test_mode: false
random_state: 42
verbose: true
variant_filtering:
  use_variant_filtering: true
  variant_filtering_upper_bound: 0.09
  variant_filtering_lower_bound: 0
