paths:
  assemblies:
    HG38: /home/users/roeizucker/tests/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /home/users/roeizucker/.cache/huggingface/datasets/generator
  raw_data_path: /home/users/roeizucker/tests/downloaded_datasets/GSM5652238_Liver-Hepatocytes-Z00000431.hg38.bigwig
  intermediate_train_data_path: /home/users/roeizucker/tests/huggingface_datasets_dir/_full_liver/temp_train2026-05-0108:25:07.042281.csv
  intermediate_test_data_path: /home/users/roeizucker/tests/huggingface_datasets_dir/_full_liver/temp_test2026-05-0108:25:07.042281.csv
  hf_dataset_train_path: /home/users/roeizucker/tests/huggingface_datasets_dir/_full_liver/31_retrain_full_liver_seq_600_datasets_train
  hf_dataset_test_path: /home/users/roeizucker/tests/huggingface_datasets_dir/_full_liver/31_retrain_full_liver_seq_600_datasets_test
task:
  type: cpg_extraction
  assembly: HG38
  value_column: methyl_rate
  input_mode: raw_input
  seq_size: 600
  test_size: 0.2
  blank_label: -100
  use_fasta: true
  shuffle: true
  chromosomes:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  tokenizer_name: InstaDeepAI/nucleotide-transformer-2.5b-multi-species
  output_preprocessed_data: false
  output_intermediate_data: true
  output_hf_dataset: true
  window_type: standart_no_overlap
  override_dataset: false
  train_test_seperation: kmer_sample_filtration
  clear_generator_cache: true
  replace_min1: false
testing_params:
  test_mode: false
random_state: 42
verbose: true
variant_filtering:
  use_variant_filtering: false
  variant_filtering_upper_bound: -1
  variant_filtering_lower_bound: -1
