paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /sci/archive/michall/roeizucker/huggingface_modles_cache/datasets/generator
  variant_file_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/_sixteen_liver_window/4M_per_varaint_variability_sixteen_liver_window_seq_5400_datasets.csv
  model_paths:
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_sixteen_liver_window/4M_pretrain_sixteen_liver_window_lr_1e-06_bs_2_seq_5400_testsize_0.2/epoch-2-step-50878
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_sixteen_liver_window/4M_epoch-2-step-50878_retrain_sixteen_liver_window_lr_1e-06_bs_2_seq_5400_testsize_0.2/epoch-2-step-8386
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_sixteen_liver_window/4M_epoch-2-step-50878_retrain_sixteen_liver_window_lr_1e-06_bs_2_seq_5400_testsize_0.2/epoch-9-step-37737
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_sixteen_liver_window/4M_epoch-2-step-50878_retrain_sixteen_liver_window_lr_1e-06_bs_2_seq_5400_testsize_0.2/epoch-4-step-16772
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_sixteen_liver_window/4M_epoch-2-step-50878_retrain_sixteen_liver_window_lr_1e-06_bs_2_seq_5400_testsize_0.2/epoch-8-step-33544
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_sixteen_liver_window/4M_epoch-2-step-50878_retrain_sixteen_liver_window_lr_1e-06_bs_2_seq_5400_testsize_0.2/epoch-7-step-29351
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_sixteen_liver_window/4M_epoch-2-step-50878_retrain_sixteen_liver_window_lr_1e-06_bs_2_seq_5400_testsize_0.2/epoch-1-step-4193
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_sixteen_liver_window/4M_epoch-2-step-50878_retrain_sixteen_liver_window_lr_1e-06_bs_2_seq_5400_testsize_0.2/epoch-5-step-20965
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_sixteen_liver_window/4M_epoch-2-step-50878_retrain_sixteen_liver_window_lr_1e-06_bs_2_seq_5400_testsize_0.2/epoch-3-step-12579
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_sixteen_liver_window/4M_epoch-2-step-50878_retrain_sixteen_liver_window_lr_1e-06_bs_2_seq_5400_testsize_0.2/epoch-6-step-25158
  - /sci/labs/michall/roeizucker/trained_huggingface_models_location/_sixteen_liver_window/4M_epoch-2-step-50878_retrain_sixteen_liver_window_lr_1e-06_bs_2_seq_5400_testsize_0.2/epoch-10-step-41930
  dataset_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/_sixteen_liver_window/4M_retrain_sixteen_liver_window_seq_5400_datasets_test
task:
  task_type: cpg_evaluation
  sub_task: evaluate_multiple_checkpoints
  analysis_name: 4M_epoch-2-step-50878_eval_sixteen_liver_window_lr_1e-06_bs_2_seq_5400_testsize_0.2
  top_rows: -1
  use_variant_file: true
  vriant_grouping_method: bins
  number_of_bins: 5
  base_suffix: _sixteen_liver_window
testing_params:
  test_mode: false
random_state: 42
verbose: true
model:
  model_name: nucleotide-transformer-2.5b-multi-species
  model_repo: InstaDeepAI
  model_type: regression_analysis
  blank_label: -100
  use_lora: false
  freeze_mode: false
  num_labels: 1
  lora_over_finetuned: false
