paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /sci/archive/michall/roeizucker/huggingface_modles_cache/datasets/generator
  raw_data_paths:
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652212_Heart-Cardiomyocyte-Z0000044G.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652213_Heart-Cardiomyocyte-Z0000044K.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652215_Heart-Cardiomyocyte-Z0000044P.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652216_Heart-Cardiomyocyte-Z0000044Q.hg38.bigwig
  - /sci/archive/michall/roeizucker/downloaded_datasets/GSM5652217_Heart-Cardiomyocyte-Z0000044R.hg38.bigwig
  per_variant_data_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/_sixteen_shards_of_adonalsium_Heart_Cardiomyocyte/4N_per_varaint_variability_sixteen_shards_of_adonalsium_Heart_Cardiomyocyte_seq_5400_datasets.csv
task:
  type: cpg_seperating_sites
  chromosomes:
  - chr19
  test_size: 0
  variability_type: std
  variant_seperation_type: quantile
  variant_seperation_threshold: 0.09
  output_per_variant_data: true
  output_window_data: false
  seq_size: 5400
testing_params:
  test_mode: false
random_state: 42
verbose: true
