params : 
    project_suffix                : _test_no_grad_norm_without_fp_or_variability_change
    bigwig_files                  : ['/sci/archive/michall/roeizucker/downloaded_datasets/GSM5652233_Liver-Hepatocytes-Z000000R3.hg38.bigwig', '/sci/archive/michall/roeizucker/downloaded_datasets/GSM5652234_Liver-Hepatocytes-Z000000T3.hg38.bigwig', '/sci/archive/michall/roeizucker/downloaded_datasets/GSM5652235_Liver-Hepatocytes-Z0000043Q.hg38.bigwig']
    names                         : ['R3', 'T3', '3Q']
    created_configs_path          : /cs/usr/roeizucker/new_storage/jupyter_notebooks/Tom_Hope_Project/refactored_code/configs/_test_no_grad_norm_without_fp_or_variability_change
    tokenizer_name                : InstaDeepAI/nucleotide-transformer-2.5b-multi-species
    dataset_base_dir              : /sci/archive/michall/roeizucker/huggingface_datasets_dir/
    base_model_location           : /sci/archive/michall/roeizucker/trained_huggingfacce_models_location
    model_type                    : regression_analysis
    use_lora                      : False
    freeze_model                  : False
    num_labels                    : 1
    load_best_model_at_end        : False
    num_train_epoch               : 3
    per_device_train_batch_size   : 2
    per_device_eval_batch_size    : 2
    learning_rate                 : 1e-05
    metric_for_best_model         : mse
    save_stratagy                 : steps
    number_of_steps               : 500
    save_total_limit              : 20
    add_epoch_end_save_callback   : True
    save_at_end                   : False
    continue_from_last            : True
    use_variant_filtering         : True
    variant_filtering_upper_bound : 0.09
    variant_filtering_lower_bound : 0
    top_rows                      : 2000
    top_rows                      : 2000