# config.yaml

paths:
  assemblies:
    HG38: "/sci/archive/michall/roeizucker/reference_genome/hg38.fa"
    MM10: "/sci/archive/michall/roeizucker/reference_genome/mm10.fa"
  created_datasets: "/sci/archive/michall/roeizucker/Tom_project/created_datasets"
  train_dataset_path: [
    "/sci/archive/michall/roeizucker/huggingface_datasets_dir/ENCFF854OPR_retrain_dataset_train"
    ]
  output_dir : "/sci/archive/michall/roeizucker/trained_huggingfacce_models_location/ENCFF854OPR_retrain_all_chrom"
  trained_model_path : "/sci/archive/michall/roeizucker/trained_huggingfacce_models_location/ENCFF713LYH_ENCFF479QRW_all_chrom_first_test_killable/checkpoint-537752"

task:
  task_type: "cpg_retraining"
  # sub_task: "evaluate_single_checkpoint"
  analysis_name : "ENCFF854OPR_retrain_all_chrom"
  assembly:       "HG38"
  test_dataset:   "fill here"
  train_dataset:   false
  sequence_col: "sequence"   # name of the field in your Dataset
  label_col:    "labels"     # name of the field holding per‐base label lists
  top_rows: -1  # number of rows to evaluate, set to -1 for all rows

model:
  model_name: "nucleotide-transformer-500m-1000g"
  model_repo: "InstaDeepAI" 
  model_type: "regression_analysis"  # or "CLASSIFICATION_ANALYSIS
  blank_label: -100
  use_lora : true
  freeze_model : true
  num_labels: 1  # for regression, set to 1; for classification, set to the number of classes

train:
  load_best_model_at_end : false
  num_train_epochs : 3
  per_device_train_batch_size : 2
  per_device_eval_batch_size : 2
  learning_rate : 1e-5
  metric_for_best_model: "mse"
  resample_rate : 0.1
  

testing_params:
  test_mode: false
evaluation:
  batch_size:     16
  device:         "cuda"
  num_workers:    4
  threshold:      0.5
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - roc_auc
    - pr_auc
    - mcc

  # Output filenames are now provided under paths

verbose: true
random_state: 42
