paths:
  assemblies:
    HG38: /sci/archive/michall/roeizucker/reference_genome/hg38.fa
    MM10: /sci/archive/michall/roeizucker/reference_genome/mm10.fa
  generetor_cache_dir: /sci/archive/michall/roeizucker/huggingface_modles_cache/datasets/generator
  variant_file_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/_HPO_after_time_improvment/3Q_per_varaint_variability_HPO_after_time_improvment_datasets.csv
  model_paths:
  - /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/_HPO_after_time_improvment/3Q_pretrain_HPO_after_time_improvment_lr_1e-05_bs_2_seq_5400_testsize_0.2/epoch-1-step-32665
  - /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/_HPO_after_time_improvment/3Q_epoch-1-step-32665_retrain_lora_HPO_after_time_improvment_lr_1e-05_bs_2_seq_5400_testsize_0.2/epoch-3-step-49374
  - /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/_HPO_after_time_improvment/3Q_epoch-1-step-32665_retrain_lora_HPO_after_time_improvment_lr_1e-05_bs_2_seq_5400_testsize_0.2/epoch-1-step-16458
  - /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/_HPO_after_time_improvment/3Q_epoch-1-step-32665_retrain_lora_HPO_after_time_improvment_lr_1e-05_bs_2_seq_5400_testsize_0.2/epoch-4-step-65832
  - /sci/archive/michall/roeizucker/trained_huggingfacce_models_location/_HPO_after_time_improvment/3Q_epoch-1-step-32665_retrain_lora_HPO_after_time_improvment_lr_1e-05_bs_2_seq_5400_testsize_0.2/epoch-2-step-32916
  dataset_path: /sci/archive/michall/roeizucker/huggingface_datasets_dir/_HPO_after_time_improvment/3Q_retrain_HPO_after_time_improvment_datasets_test
task:
  task_type: cpg_evaluation
  sub_task: evaluate_multiple_checkpoints
  analysis_name: 3Q_epoch-1-step-32665_eval_lora_HPO_after_time_improvment_lr_1e-05_bs_2_seq_5400_testsize_0.2
  top_rows: -1
  use_variant_file: true
  vriant_grouping_method: bins
  number_of_bins: 5
  base_suffix: _HPO_after_time_improvment
testing_params:
  test_mode: false
random_state: 42
verbose: true
model:
  model_name: nucleotide-transformer-2.5b-multi-species
  model_repo: InstaDeepAI
  model_type: regression_analysis
  blank_label: -100
  use_lora: true
  freeze_mode: true
  num_labels: 1
